[phases.setup]
nixPkgs = ['nodejs_20', 'python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'npm ci',
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[start]
cmd = 'bash start.sh'
